language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "UVP8els50rVNZ6LjTHzhjgm0nq5Opc9t100/lsR0Qr8vEPcnJj7ZgyUlN4TFYcqREo3oOo1MXVfU+78up8NqMcYdl
HiyBNRsqUuSRpzbLabbDlKF7DARje3M7QySMYw3g93aXvyipi4rIQIkDboV+tcZGUHJV1A8zEcqLxtCNc19swqLRYWhLzuf+36CI
xhCn+h6FZROkSUQ5hfqIGb1x6VsrS9PV3unG9x1N8pie2O4CEE0z8B3KzYB2kgQ+8PDVZNEH983i1Ez4zzluDYeUTarcC0kQzYdZ
B9lPef5Ce+fG0c083codGXakR5yIljdJ9vkZxEAVzxM9gZvH5V7DzvrfaPMPFax2d+MIbtMvgoKWuOvl90bjGFAuJGBhvGMeDJ/n
cBqg8E+IArosXrtfRGE+3KITohYSNnXXdI3Tf0W12jRMoyAKPWiZljQpYMz1QdZmHDa/PC4NSMpMbwwwQCoXN8n/nkYAX5fh6Gwl
5csumymcfW84NQoAxLJR3hcfMiHV2qTFSW+H4Up+VyYAYYILofRZKvkPC+P+yZ4lgwk5A2Mb9TtZ/74rw+3lnmfz6XWP2Hpub+EU
2Tojh0RXSMSIWqr9wCLgt7RBYCdhM9l59QBNmYaV8PoFLazVZUZ7Z44LJ4LCVrH4CXQfd9xnL0kjsFoQE6QoSx6/D0WA1s="

jdk:
  - oraclejdk8
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
